name: Deploy Backend (Strapi) to Railway

on:
    push:
        paths:
            - "backend/**"
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install Railway CLI
              run: npm install -g @railway/cli

            - name: Set Railway API Key
              run: echo "RAILWAY_API_KEY=${{ secrets.RAILWAY_TOKEN }}" >> $GITHUB_ENV

            - name: Deploy to Railway
              run: |
                  cd backend
                  railway up
